// ─── Central Mock Data ────────────────────────────────────────────────────────
// Represents all public-facing database tables. Used by all public pages.

// ── Amenities ──────────────────────────────────────────────────────────────
export const MOCK_AMENITIES = [
  { id: 1, name: 'Swimming Pool' },
  { id: 2, name: 'Fitness Gym' },
  { id: 3, name: 'Covered Parking' },
  { id: 4, name: 'Playground' },
  { id: 5, name: 'Basketball Court' },
  { id: 6, name: 'Tennis Court' },
  { id: 7, name: 'Clubhouse' },
  { id: 8, name: 'Landscaped Garden' },
  { id: 9, name: '24/7 CCTV' },
  { id: 10, name: '24/7 Security' },
  { id: 11, name: 'Wi-Fi Common Areas' },
  { id: 12, name: 'Function Room' },
  { id: 13, name: 'Jogging Path' },
  { id: 14, name: 'Badminton Court' },
  { id: 15, name: 'Yoga Studio' },
  { id: 16, name: "Kids' Pool" },
  { id: 17, name: 'Sky Lounge' },
  { id: 18, name: 'Business Center' },
  { id: 19, name: 'Concierge Service' },
  { id: 20, name: 'Visitor Parking' },
]

// ── OFW News (Dummy) ───────────────────────────────────────────────────────
export const MOCK_OFW_NEWS = [
  {
    id: 201,
    title: 'The Complete Guide for OFWs Buying Property in the Philippines',
    slug: 'ofw-complete-guide',
    category: 'Guides',
    tags: ['OFW', 'Guide', 'Financing'],
    image_url: 'https://picsum.photos/seed/ofw1/800/500',
    excerpt: 'Everything an overseas Filipino worker needs to know about purchasing property back home...',
    published_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 202,
    title: 'OFW Investment Opportunities: Bring Hope to Distressed Dry Sites',
    slug: 'ofw-investment-dry-sites',
    category: 'Investment',
    tags: ['OFW', 'Investment'],
    image_url: 'https://picsum.photos/seed/ofw2/800/500',
    excerpt: 'How OFWs can help revitalize underutilized properties and create community value...',
    published_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 203,
    title: 'Doha: OFWs Investing in Overseascondominiums Path for Overseas Growth',
    slug: 'ofw-doha-investments',
    category: 'Regional Update',
    tags: ['OFW'],
    image_url: 'https://picsum.photos/seed/ofw3/800/500',
    excerpt: 'Insights into why OFWs in the Middle East are turning to Philippine real estate...',
    published_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 204,
    title: "South Korea's OFW Travel Guide: What I K-Pop Boom Means for Filipino Investors",
    slug: 'ofw-korea-kpop',
    category: 'Guides',
    tags: ['OFW', 'Guide'],
    image_url: 'https://picsum.photos/seed/ofw4/800/500',
    excerpt: 'Exploring how the K-pop wave and cultural shift create new investment opportunities...',
    published_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 205,
    title: "Toronto's New Investment Stabilization in the Philippines",
    slug: 'ofw-toronto-invest',
    category: 'Investment',
    tags: ['OFW', 'Investment'],
    image_url: 'https://picsum.photos/seed/ofw5/800/500',
    excerpt: 'Canadian OFWs are finding stable returns investing in Philippine real estate...',
    published_at: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 206,
    title: 'OFW Success Stories: From Migrant Workers to Property Owners',
    slug: 'ofw-success-stories',
    category: 'Guides',
    tags: ['OFW', 'Guide', 'Success Stories'],
    image_url: 'https://picsum.photos/seed/ofw6/800/500',
    excerpt: 'Real tales of OFWs who achieved financial independence through smart property investments...',
    published_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 207,
    title: 'Remittance Trends 2026: How OFW Money Is Reshaping Philippine Real Estate',
    slug: 'ofw-remittance-trends',
    category: 'Investment',
    tags: ['OFW', 'Investment', 'Market Trends'],
    image_url: 'https://picsum.photos/seed/ofw7/800/500',
    excerpt: 'Record remittances from abroad are driving unprecedented demand in the residential property market...',
    published_at: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 208,
    title: 'Gulf Countries: Where OFWs Are Buying Secondary Homes Back Home',
    slug: 'ofw-gulf-buying-homes',
    category: 'Regional Update',
    tags: ['OFW', 'Investment'],
    image_url: 'https://picsum.photos/seed/ofw8/800/500',
    excerpt: 'OFWs in Saudi Arabia, UAE, and Qatar are increasingly purchasing investment properties...',
    published_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 209,
    title: 'Financial Planning for OFWs: Building Wealth Through Real Estate',
    slug: 'ofw-financial-planning',
    category: 'Guides',
    tags: ['OFW', 'Guide', 'Financing'],
    image_url: 'https://picsum.photos/seed/ofw9/800/500',
    excerpt: 'A comprehensive guide to managing finances and building a property portfolio as an OFW...',
    published_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 210,
    title: 'OFW Home Buyers: Navigating Overseas Bank Transfers and Financing',
    slug: 'ofw-overseas-transfers',
    category: 'Guides',
    tags: ['OFW', 'Guide', 'Financing'],
    image_url: 'https://picsum.photos/seed/ofw10/800/500',
    excerpt: 'Expert advice on how to transfer money from abroad and secure financing for your own property...',
    published_at: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 211,
    title: 'Asia-Pacific OFW Market: Where Filipinos Are Investing Beyond the Middle East',
    slug: 'asia-pacific-ofw-market',
    category: 'Regional Update',
    tags: ['OFW', 'Investment', 'Market Trends'],
    image_url: 'https://picsum.photos/seed/ofw11/800/500',
    excerpt: 'Investors from Singapore, Malaysia, and Hong Kong are increasingly looking at Philippine real estate...',
    published_at: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 212,
    title: 'Rental Income for OFWs: Passive Returns While You Work Abroad',
    slug: 'ofw-rental-income',
    category: 'Investment',
    tags: ['OFW', 'Investment', 'Passive Income'],
    image_url: 'https://picsum.photos/seed/ofw12/800/500',
    excerpt: 'Learn how OFWs can generate steady rental income from Philippine properties while earning a salary abroad...',
    published_at: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 213,
    title: 'OFW Co-ownership: Pooling Funds for Bigger Property Deals',
    slug: 'ofw-co-ownership',
    category: 'Investment',
    tags: ['OFW', 'Investment'],
    image_url: 'https://picsum.photos/seed/ofw13/800/500',
    excerpt: 'Small groups of OFWs are co-investing in multi-unit properties to unlock better returns and risk sharing...',
    published_at: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 214,
    title: 'Visa, Remittance, and Tax: A Practical Toolkit for OFW Investors',
    slug: 'ofw-practical-toolkit',
    category: 'Guides',
    tags: ['OFW', 'Guide', 'Financing'],
    image_url: 'https://picsum.photos/seed/ofw14/800/500',
    excerpt: 'A handy checklist to navigate bank transfers, documentation, and compliance when buying property from abroad...',
    published_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

// ── Property Types ──────────────────────────────────────────────────────────
export const MOCK_PROPERTY_TYPES = [
  { id: 1, name: 'Condominium' },
  { id: 2, name: 'House & Lot' },
  { id: 3, name: 'Townhouse' },
  { id: 4, name: 'Commercial Space' },
  { id: 5, name: 'Lot Only' },
  { id: 6, name: 'Warehouse' },
  { id: 7, name: 'Office Space' },
]

// ── Developers ─────────────────────────────────────────────────────────────
export const MOCK_DEVELOPERS = [
  {
    id: 1,
    developer_name: 'Ayala Land Inc.',
    industry: 'Real Estate Development',
    website_url: 'https://www.ayalaland.com.ph',
    description:
      'Ayala Land is one of the Philippines\' largest property developers, with a 30-year track record of building integrated, mixed-use communities that blend residential, commercial, and leisure spaces across the archipelago.',
    logo_url: 'https://picsum.photos/seed/ayala/200/200',
    founded: '1988',
    projects_count: 15,
    contact: {
      primary_mobile: '+63 917 888 1234',
      telephone: '(02) 8908-3000',
      email: 'customercare@ayalaland.com.ph',
      facebook_url: 'https://www.facebook.com/AyalaLandInc',
      linkedin_url: 'https://www.linkedin.com/company/ayala-land',
      instagram_url: 'https://www.instagram.com/ayalalandofficial',
    },
    contact_persons: [
      { id: 1, full_name: 'Maria Santos', position: 'Sales Director', email: 'm.santos@ayalaland.com.ph', mobile_number: '+63 917 555 1001' },
      { id: 2, full_name: 'Jose Reyes', position: 'Project Manager', email: 'j.reyes@ayalaland.com.ph', mobile_number: '+63 917 555 1002' },
    ],
    address: 'Tower One & Exchange Plaza, Ayala Triangle, Makati City',
    stats: { projects: 15, units: 8500, provinces: 7 },
  },
  {
    id: 2,
    developer_name: 'SM Prime Holdings',
    industry: 'Mixed-Use Development',
    website_url: 'https://www.smprime.com',
    description:
      'SM Prime Holdings is a market leader in integrated property development in the Philippines. Their portfolio includes malls, residences, offices, hotels, and convention centers that create vibrant communities across the country.',
    logo_url: 'https://picsum.photos/seed/smprime/200/200',
    founded: '1994',
    projects_count: 12,
    contact: {
      primary_mobile: '+63 917 888 2234',
      telephone: '(02) 8840-7100',
      email: 'smresidences@smprime.com',
      facebook_url: 'https://www.facebook.com/SMPrimeHoldings',
      instagram_url: 'https://www.instagram.com/smresidences',
    },
    contact_persons: [
      { id: 3, full_name: 'Ana Lim', position: 'VP Sales', email: 'a.lim@smprime.com', mobile_number: '+63 918 555 2001' },
    ],
    address: 'SM Mall of Asia Complex, Pasay City, Metro Manila',
    stats: { projects: 12, units: 10200, provinces: 9 },
  },
  {
    id: 3,
    developer_name: 'Robinsons Land Corp',
    industry: 'Residential & Commercial',
    website_url: 'https://www.robinsonsland.com',
    description:
      'Robinsons Land Corporation is a leading Philippine property developer offering a wide range of residential developments from condominiums to house-and-lot projects. Known for quality construction and community-centric designs.',
    logo_url: 'https://picsum.photos/seed/robinsons/200/200',
    founded: '1980',
    projects_count: 10,
    contact: {
      primary_mobile: '+63 917 888 3234',
      telephone: '(02) 8397-1400',
      email: 'homes@robinsonsland.com',
      facebook_url: 'https://www.facebook.com/RobinsonsHomes',
    },
    contact_persons: [
      { id: 4, full_name: 'Carlos Tan', position: 'Sales Manager', email: 'c.tan@robinsons.com', mobile_number: '+63 919 555 3001' },
    ],
    address: '43/F Robinsons Equitable Tower, ADB Avenue, Pasig City',
    stats: { projects: 10, units: 6800, provinces: 6 },
  },
  {
    id: 4,
    developer_name: 'Federal Land Inc.',
    industry: 'Luxury Real Estate',
    website_url: 'https://www.federalland.com.ph',
    description:
      'Federal Land is a distinguished Philippine property developer with over 45 years of experience creating luxury vertical and horizontal communities. Best known for mid-range to high-end condominiums in Metro Manila.',
    logo_url: 'https://picsum.photos/seed/federal/200/200',
    founded: '1972',
    projects_count: 8,
    contact: {
      primary_mobile: '+63 917 888 4234',
      telephone: '(02) 8988-4000',
      email: 'info@federalland.com.ph',
      facebook_url: 'https://www.facebook.com/FederalLandInc',
    },
    contact_persons: [
      { id: 5, full_name: 'Patricia Cruz', position: 'Senior Sales Consultant', email: 'p.cruz@federalland.com.ph', mobile_number: '+63 920 555 4001' },
    ],
    address: 'Ground Floor, GT Tower Center, Ayala Ave., Makati City',
    stats: { projects: 8, units: 4200, provinces: 3 },
  },
  {
    id: 5,
    developer_name: 'DMCI Homes',
    industry: 'Residential Condominiums',
    website_url: 'https://www.dmcihomes.com',
    description:
      'DMCI Homes, a subsidiary of D.M. Consunji Inc., is a top condominium developer in Metro Manila known for modern resort-inspired living communities. Their projects feature lush greenery, resort-style amenities and quality construction.',
    logo_url: 'https://picsum.photos/seed/dmci/200/200',
    founded: '1995',
    projects_count: 9,
    contact: {
      primary_mobile: '+63 917 888 5234',
      telephone: '(02) 8888-3000',
      email: 'customercare@dmcihomes.com',
      facebook_url: 'https://www.facebook.com/DMCIHomesOfficial',
    },
    contact_persons: [
      { id: 6, full_name: 'Roberto Garcia', position: 'Sales Consultant', email: 'r.garcia@dmcihomes.com', mobile_number: '+63 921 555 5001' },
    ],
    address: 'DMCI Plaza, 2281 Don Chino Roces Ave., Makati City',
    stats: { projects: 9, units: 7100, provinces: 2 },
  },
  {
    id: 6,
    developer_name: 'Megaworld Corp',
    industry: 'Township Development',
    website_url: 'https://www.megaworldcorp.com',
    description:
      'Megaworld Corporation is the leading developer of integrated urban townships in the Philippines. Best known for pioneering the live-work-play concept through landmark townships like the McKinley Hill in Taguig and Iloilo Business Park.',
    logo_url: 'https://picsum.photos/seed/megaworld/200/200',
    founded: '1989',
    projects_count: 14,
    contact: {
      primary_mobile: '+63 917 888 6234',
      telephone: '(02) 8789-3300',
      email: 'customerservice@megaworldcorp.com',
      facebook_url: 'https://www.facebook.com/MegaworldCorporation',
    },
    contact_persons: [
      { id: 7, full_name: 'Elena Villanueva', position: 'Regional Sales Head', email: 'e.villanueva@megaworld.com', mobile_number: '+63 922 555 6001' },
    ],
    address: '28th Floor, The World Centre, 330 Sen. Gil Puyat Ave., Makati City',
    stats: { projects: 14, units: 11000, provinces: 8 },
  },
  {
    id: 7,
    developer_name: 'Vista Land & Residences',
    industry: 'Horizontal Housing',
    website_url: 'https://www.vistaland.com.ph',
    description:
      "Vista Land & Lifescapes is the Philippines' largest homebuilder with a diverse portfolio of house-and-lot projects ranging from affordable to premium segments. Their brand portfolio includes Camella Homes, Crown Asia, and Vista Residences.",
    logo_url: 'https://picsum.photos/seed/vistaland/200/200',
    founded: '1977',
    projects_count: 20,
    contact: {
      primary_mobile: '+63 917 888 7234',
      telephone: '(02) 8584-2700',
      email: 'customercare@vistaland.com.ph',
      facebook_url: 'https://www.facebook.com/vistaland',
    },
    contact_persons: [
      { id: 8, full_name: 'Michael Dela Cruz', position: 'Sales Director', email: 'm.delacruz@vistaland.com', mobile_number: '+63 923 555 7001' },
    ],
    address: '8th Floor, 8 Rockwell, Rockwell Center, Makati City',
    stats: { projects: 20, units: 45000, provinces: 20 },
  },
  {
    id: 8,
    developer_name: 'Filinvest Land',
    industry: 'Integrated Community Development',
    website_url: 'https://www.filinvestland.com',
    description:
      'Filinvest Land, Inc. is a leading diversified real estate developer in the Philippines making quality homes and commercial facilities accessible and affordable. Their integrated community approach combines residential, retail, and office spaces into master-planned estates.',
    logo_url: 'https://picsum.photos/seed/filinvest/200/200',
    founded: '1993',
    projects_count: 11,
    contact: {
      primary_mobile: '+63 917 888 8234',
      telephone: '(02) 8850-0988',
      email: 'customercare@filinvestland.com',
      facebook_url: 'https://www.facebook.com/FilinvestLand',
    },
    contact_persons: [
      { id: 9, full_name: 'Grace Mendoza', position: 'Sales Manager', email: 'g.mendoza@filinvest.com', mobile_number: '+63 924 555 8001' },
    ],
    address: 'Filinvest Corporate City, Alabang, Muntinlupa City',
    stats: { projects: 11, units: 9400, provinces: 6 },
  },
]

// ── Projects ────────────────────────────────────────────────────────────────
export const MOCK_PROJECTS = [
  {
    id: 1,
    uuid: 'proj-uuid-001',
    name: 'One Serendra',
    slug: 'one-serendra',
    developer_id: 1,
    developers_profiles: { id: 1, developer_name: 'Ayala Land Inc.', logo_url: 'https://picsum.photos/seed/ayala/200/200' },
    lts_number: 'LTS-2021-001234',
    lts_issued_date: '2021-03-15',
    dhsud_registration_number: 'DHSUD-NCR-2021-0056',
    project_type: 'High-Rise Condominium',
    classification: 'Premium',
    region: 'NCR',
    province: 'Metro Manila',
    city_municipality: 'Taguig City',
    barangay: 'BGC',
    island_group: 'Luzon',
    address_details: 'Bonifacio Global City, Taguig, Metro Manila',
    latitude: 14.5497,
    longitude: 121.0500,
    status: 'Ready for Occupancy',
    expected_completion_date: '2022-12-01',
    turnover_date: '2023-06-01',
    currency: 'PHP',
    price_range_min: 8500000,
    price_range_max: 35000000,
    average_price: 18000000,
    vat_inclusive: true,
    main_image_url: 'https://picsum.photos/seed/onese/900/600',
    video_tour_url: null,
    is_featured: true,
    amenity_ids: [1, 2, 3, 7, 9, 10, 17, 18, 19],
    project_amenities: [
      { amenities: { id: 1, name: 'Swimming Pool' } },
      { amenities: { id: 2, name: 'Fitness Gym' } },
      { amenities: { id: 3, name: 'Covered Parking' } },
      { amenities: { id: 7, name: 'Clubhouse' } },
      { amenities: { id: 10, name: '24/7 Security' } },
      { amenities: { id: 17, name: 'Sky Lounge' } },
      { amenities: { id: 18, name: 'Business Center' } },
    ],
    project_galleries: [
      { id: 1, image_url: 'https://picsum.photos/seed/onese1/900/600', title: 'Tower Exterior', display_order: 0 },
      { id: 2, image_url: 'https://picsum.photos/seed/onese2/900/600', title: 'Pool Deck', display_order: 1 },
      { id: 3, image_url: 'https://picsum.photos/seed/onese3/900/600', title: 'Living Area', display_order: 2 },
      { id: 4, image_url: 'https://picsum.photos/seed/onese4/900/600', title: 'Master Bedroom', display_order: 3 },
    ],
    project_units: [
      { id: 1, unit_name: 'Studio', unit_type: 'Studio', floor_area_sqm: 28, lot_area_sqm: null, bedrooms: 0, bathrooms: 1, has_balcony: false, has_parking: false, is_furnished: 'Unfurnished', status: 'Available', selling_price: 8500000 },
      { id: 2, unit_name: '1-Bedroom', unit_type: '1 Bedroom', floor_area_sqm: 42, lot_area_sqm: null, bedrooms: 1, bathrooms: 1, has_balcony: true, has_parking: true, is_furnished: 'Semi-Furnished', status: 'Available', selling_price: 12500000 },
      { id: 3, unit_name: '2-Bedroom', unit_type: '2 Bedroom', floor_area_sqm: 68, lot_area_sqm: null, bedrooms: 2, bathrooms: 2, has_balcony: true, has_parking: true, is_furnished: 'Semi-Furnished', status: 'Available', selling_price: 18000000 },
      { id: 4, unit_name: '3-Bedroom', unit_type: '3 Bedroom', floor_area_sqm: 95, lot_area_sqm: null, bedrooms: 3, bathrooms: 2, has_balcony: true, has_parking: true, is_furnished: 'Fully Furnished', status: 'Available', selling_price: 28000000 },
    ],
    faqs: [
      { id: 1, question: 'What is the turnover date?', answer: 'The expected turnover date is Q2 2023. Units are being handed over on a rolling basis starting June 2023.' },
      { id: 2, question: 'Is parking included in the price?', answer: 'Parking is optional for Studio units and included in 1BR up. Each parking slot is separately priced at ₱1,200,000.' },
      { id: 3, question: 'What payment terms are available?', answer: 'We offer flexible payment terms: 10% spot down payment, 10% spread over 24 months, balance through bank financing or in-house financing.' },
      { id: 4, question: 'Are pets allowed?', answer: 'One pet (up to 10kg) is allowed per unit with proper registration with the building administration.' },
    ],
  },
  {
    id: 2,
    uuid: 'proj-uuid-002',
    name: 'Breeze Residences',
    slug: 'breeze-residences',
    developer_id: 2,
    developers_profiles: { id: 2, developer_name: 'SM Prime Holdings', logo_url: 'https://picsum.photos/seed/smprime/200/200' },
    lts_number: 'LTS-2020-005678',
    project_type: 'Mid-Rise Condominium',
    classification: 'Mid-Range',
    region: 'NCR',
    province: 'Metro Manila',
    city_municipality: 'Pasay City',
    barangay: 'Mall of Asia',
    island_group: 'Luzon',
    address_details: 'SM Mall of Asia Complex, Pasay City',
    latitude: 14.5354,
    longitude: 120.9834,
    status: 'Pre-Selling',
    expected_completion_date: '2026-06-01',
    currency: 'PHP',
    price_range_min: 4500000,
    price_range_max: 12000000,
    average_price: 7000000,
    vat_inclusive: true,
    main_image_url: 'https://picsum.photos/seed/breeze/900/600',
    is_featured: true,
    amenity_ids: [1, 2, 4, 7, 9, 10, 11, 13],
    project_amenities: [
      { amenities: { id: 1, name: 'Swimming Pool' } },
      { amenities: { id: 2, name: 'Fitness Gym' } },
      { amenities: { id: 4, name: 'Playground' } },
      { amenities: { id: 7, name: 'Clubhouse' } },
      { amenities: { id: 9, name: '24/7 CCTV' } },
      { amenities: { id: 13, name: 'Jogging Path' } },
    ],
    project_galleries: [
      { id: 5, image_url: 'https://picsum.photos/seed/breeze1/900/600', title: 'Building Facade', display_order: 0 },
      { id: 6, image_url: 'https://picsum.photos/seed/breeze2/900/600', title: 'Amenity Area', display_order: 1 },
      { id: 7, image_url: 'https://picsum.photos/seed/breeze3/900/600', title: 'Sample Unit', display_order: 2 },
    ],
    project_units: [
      { id: 5, unit_name: 'Studio', unit_type: 'Studio', floor_area_sqm: 24, bedrooms: 0, bathrooms: 1, has_balcony: false, has_parking: false, status: 'Available', selling_price: 4500000 },
      { id: 6, unit_name: '1-Bedroom', unit_type: '1 Bedroom', floor_area_sqm: 38, bedrooms: 1, bathrooms: 1, has_balcony: true, has_parking: true, status: 'Available', selling_price: 6800000 },
      { id: 7, unit_name: '2-Bedroom', unit_type: '2 Bedroom', floor_area_sqm: 56, bedrooms: 2, bathrooms: 2, has_balcony: true, has_parking: true, status: 'Available', selling_price: 9500000 },
    ],
    faqs: [
      { id: 5, question: 'When is the expected completion?', answer: 'The project is expected to be completed by Q2 2026 with turnover starting Q4 2026.' },
      { id: 6, question: 'Is the Mall of Asia nearby?', answer: 'Yes! The SM Mall of Asia is directly accessible from the development, within 3-5 minutes walking distance.' },
    ],
  },
  {
    id: 3,
    uuid: 'proj-uuid-003',
    name: 'Galleria Residences',
    slug: 'galleria-residences',
    developer_id: 3,
    developers_profiles: { id: 3, developer_name: 'Robinsons Land Corp', logo_url: 'https://picsum.photos/seed/robinsons/200/200' },
    project_type: 'High-Rise Condominium',
    classification: 'Upper Mid-Range',
    region: 'Region VII',
    province: 'Cebu',
    city_municipality: 'Cebu City',
    barangay: 'Cebu Business Park',
    island_group: 'Visayas',
    address_details: 'Cebu Business Park, Cebu City',
    latitude: 10.3157,
    longitude: 123.8855,
    status: 'Ready for Occupancy',
    expected_completion_date: '2022-01-01',
    currency: 'PHP',
    price_range_min: 5200000,
    price_range_max: 18000000,
    average_price: 9800000,
    vat_inclusive: true,
    main_image_url: 'https://picsum.photos/seed/galleria/900/600',
    is_featured: false,
    project_amenities: [
      { amenities: { id: 1, name: 'Swimming Pool' } },
      { amenities: { id: 2, name: 'Fitness Gym' } },
      { amenities: { id: 7, name: 'Clubhouse' } },
      { amenities: { id: 10, name: '24/7 Security' } },
      { amenities: { id: 12, name: 'Function Room' } },
      { amenities: { id: 18, name: 'Business Center' } },
    ],
    project_galleries: [
      { id: 8, image_url: 'https://picsum.photos/seed/gall1/900/600', title: 'Tower View', display_order: 0 },
      { id: 9, image_url: 'https://picsum.photos/seed/gall2/900/600', title: 'Pool & Lounge', display_order: 1 },
      { id: 10, image_url: 'https://picsum.photos/seed/gall3/900/600', title: 'Sample 2BR', display_order: 2 },
    ],
    project_units: [
      { id: 8, unit_name: 'Studio', unit_type: 'Studio', floor_area_sqm: 26, bedrooms: 0, bathrooms: 1, has_balcony: false, has_parking: false, status: 'Available', selling_price: 5200000 },
      { id: 9, unit_name: '1-Bedroom', unit_type: '1 Bedroom', floor_area_sqm: 40, bedrooms: 1, bathrooms: 1, has_balcony: true, has_parking: true, status: 'Available', selling_price: 8500000 },
      { id: 10, unit_name: '2-Bedroom', unit_type: '2 Bedroom', floor_area_sqm: 60, bedrooms: 2, bathrooms: 2, has_balcony: true, has_parking: true, status: 'Available', selling_price: 14000000 },
    ],
    faqs: [
      { id: 7, question: 'Is this near Ayala Center Cebu?', answer: 'Yes, Galleria Residences is within the Cebu Business Park district, a 5-minute walk to Ayala Center Cebu.' },
    ],
  },
  {
    id: 4,
    uuid: 'proj-uuid-004',
    name: 'Camella Daang Hari',
    slug: 'camella-daang-hari',
    developer_id: 7,
    developers_profiles: { id: 7, developer_name: 'Vista Land & Residences', logo_url: 'https://picsum.photos/seed/vistaland/200/200' },
    project_type: 'House & Lot',
    classification: 'Affordable',
    region: 'Region IV-A',
    province: 'Cavite',
    city_municipality: 'Bacoor',
    barangay: 'Molino',
    island_group: 'Luzon',
    address_details: 'Daang Hari, Bacoor, Cavite',
    latitude: 14.4004,
    longitude: 120.9761,
    status: 'Ready for Occupancy',
    currency: 'PHP',
    price_range_min: 2800000,
    price_range_max: 7500000,
    average_price: 4500000,
    vat_inclusive: true,
    main_image_url: 'https://picsum.photos/seed/camella/900/600',
    is_featured: true,
    project_amenities: [
      { amenities: { id: 4, name: 'Playground' } },
      { amenities: { id: 5, name: 'Basketball Court' } },
      { amenities: { id: 7, name: 'Clubhouse' } },
      { amenities: { id: 8, name: 'Landscaped Garden' } },
      { amenities: { id: 10, name: '24/7 Security' } },
      { amenities: { id: 13, name: 'Jogging Path' } },
    ],
    project_galleries: [
      { id: 11, image_url: 'https://picsum.photos/seed/cam1/900/600', title: 'House Exterior', display_order: 0 },
      { id: 12, image_url: 'https://picsum.photos/seed/cam2/900/600', title: 'Community Park', display_order: 1 },
      { id: 13, image_url: 'https://picsum.photos/seed/cam3/900/600', title: 'Living Room', display_order: 2 },
    ],
    project_units: [
      { id: 11, unit_name: 'Freya Model', unit_type: '2-Bedroom House', floor_area_sqm: 44, lot_area_sqm: 88, bedrooms: 2, bathrooms: 1, has_balcony: false, has_parking: true, status: 'Available', selling_price: 2800000 },
      { id: 12, unit_name: 'Cara Model', unit_type: '3-Bedroom House', floor_area_sqm: 64, lot_area_sqm: 132, bedrooms: 3, bathrooms: 2, has_balcony: false, has_parking: true, status: 'Available', selling_price: 4500000 },
      { id: 13, unit_name: 'Ela Model', unit_type: '4-Bedroom House', floor_area_sqm: 95, lot_area_sqm: 180, bedrooms: 4, bathrooms: 3, has_balcony: true, has_parking: true, status: 'Available', selling_price: 7500000 },
    ],
    faqs: [
      { id: 8, question: 'How far is it from Manila?', answer: 'Camella Daang Hari is approximately 30-45 minutes from Manila via Daang Hari Road or the SLEX-CAVITEX.' },
      { id: 9, question: 'Are schools nearby?', answer: 'Several schools are nearby including De La Salle University - Dasmariñas, Pamantasan ng Lungsod ng Muntinlupa, and San Beda College.' },
    ],
  },
  {
    id: 5,
    uuid: 'proj-uuid-005',
    name: 'Satori Residences',
    slug: 'satori-residences',
    developer_id: 5,
    developers_profiles: { id: 5, developer_name: 'DMCI Homes', logo_url: 'https://picsum.photos/seed/dmci/200/200' },
    project_type: 'Mid-Rise Condominium',
    classification: 'Mid-Range',
    region: 'NCR',
    province: 'Metro Manila',
    city_municipality: 'Pasig City',
    barangay: 'Kapitolyo',
    island_group: 'Luzon',
    address_details: 'Mandaluyong-Pasig boundary, EDSA',
    latitude: 14.5765,
    longitude: 121.0436,
    status: 'Ready for Occupancy',
    currency: 'PHP',
    price_range_min: 4200000,
    price_range_max: 9800000,
    average_price: 6500000,
    vat_inclusive: true,
    main_image_url: 'https://picsum.photos/seed/satori/900/600',
    is_featured: false,
    project_amenities: [
      { amenities: { id: 1, name: 'Swimming Pool' } },
      { amenities: { id: 2, name: 'Fitness Gym' } },
      { amenities: { id: 3, name: 'Covered Parking' } },
      { amenities: { id: 7, name: 'Clubhouse' } },
      { amenities: { id: 8, name: 'Landscaped Garden' } },
      { amenities: { id: 16, name: "Kids' Pool" } },
    ],
    project_galleries: [
      { id: 14, image_url: 'https://picsum.photos/seed/sat1/900/600', title: 'Resort-Style Pool', display_order: 0 },
      { id: 15, image_url: 'https://picsum.photos/seed/sat2/900/600', title: 'Building Exterior', display_order: 1 },
      { id: 16, image_url: 'https://picsum.photos/seed/sat3/900/600', title: 'Landscaped Garden', display_order: 2 },
    ],
    project_units: [
      { id: 14, unit_name: '1-Bedroom', unit_type: '1 Bedroom', floor_area_sqm: 41, bedrooms: 1, bathrooms: 1, has_balcony: true, has_parking: true, status: 'Available', selling_price: 4200000 },
      { id: 15, unit_name: '2-Bedroom', unit_type: '2 Bedroom', floor_area_sqm: 65, bedrooms: 2, bathrooms: 2, has_balcony: true, has_parking: true, status: 'Available', selling_price: 7000000 },
    ],
    faqs: [
      { id: 10, question: 'Is there easy access to public transport?', answer: 'DMCI Satori is along EDSA with easy access to MRT stations and major bus routes.' },
    ],
  },
  {
    id: 6,
    uuid: 'proj-uuid-006',
    name: 'Iloilo Business Park Richmonde Tower',
    slug: 'iloilo-business-park-richmonde',
    developer_id: 6,
    developers_profiles: { id: 6, developer_name: 'Megaworld Corp', logo_url: 'https://picsum.photos/seed/megaworld/200/200' },
    project_type: 'High-Rise Condominium',
    classification: 'Premium',
    region: 'Region VI',
    province: 'Iloilo',
    city_municipality: 'Mandurriao',
    barangay: 'Iloilo Business Park',
    island_group: 'Visayas',
    address_details: 'Megaworld Blvd., Mandurriao, Iloilo City',
    latitude: 10.7202,
    longitude: 122.5621,
    status: 'Ready for Occupancy',
    currency: 'PHP',
    price_range_min: 3500000,
    price_range_max: 14000000,
    average_price: 7500000,
    vat_inclusive: true,
    main_image_url: 'https://picsum.photos/seed/iloilo/900/600',
    is_featured: true,
    project_amenities: [
      { amenities: { id: 1, name: 'Swimming Pool' } },
      { amenities: { id: 2, name: 'Fitness Gym' } },
      { amenities: { id: 7, name: 'Clubhouse' } },
      { amenities: { id: 10, name: '24/7 Security' } },
      { amenities: { id: 17, name: 'Sky Lounge' } },
      { amenities: { id: 18, name: 'Business Center' } },
    ],
    project_galleries: [
      { id: 17, image_url: 'https://picsum.photos/seed/ilo1/900/600', title: 'Tower Exterior', display_order: 0 },
      { id: 18, image_url: 'https://picsum.photos/seed/ilo2/900/600', title: 'City View', display_order: 1 },
      { id: 19, image_url: 'https://picsum.photos/seed/ilo3/900/600', title: 'Pool Deck', display_order: 2 },
    ],
    project_units: [
      { id: 16, unit_name: 'Studio', unit_type: 'Studio', floor_area_sqm: 25, bedrooms: 0, bathrooms: 1, has_balcony: false, has_parking: false, status: 'Available', selling_price: 3500000 },
      { id: 17, unit_name: '1-Bedroom', unit_type: '1 Bedroom', floor_area_sqm: 39, bedrooms: 1, bathrooms: 1, has_balcony: true, has_parking: true, status: 'Available', selling_price: 5800000 },
      { id: 18, unit_name: '2-Bedroom', unit_type: '2 Bedroom', floor_area_sqm: 64, bedrooms: 2, bathrooms: 2, has_balcony: true, has_parking: true, status: 'Available', selling_price: 10000000 },
    ],
    faqs: [
      { id: 11, question: 'What is nearby the Iloilo Business Park?', answer: 'The IBP is surrounded by international restaurants, retail shops, tech companies (Qualimed, KFC, Starbucks), and the award-winning Festive Walk Mall.' },
    ],
  },
  {
    id: 7,
    uuid: 'proj-uuid-007',
    name: 'Southpoint Bacolod',
    slug: 'southpoint-bacolod',
    developer_id: 8,
    developers_profiles: { id: 8, developer_name: 'Filinvest Land', logo_url: 'https://picsum.photos/seed/filinvest/200/200' },
    project_type: 'Integrated Township',
    classification: 'Mid-Range',
    region: 'Region VI',
    province: 'Bacolod',
    city_municipality: 'Bacolod City',
    barangay: 'Taculing',
    island_group: 'Visayas',
    address_details: 'Lacson St., Bacolod City, Negros Occidental',
    latitude: 10.6713,
    longitude: 122.9511,
    status: 'Pre-Selling',
    currency: 'PHP',
    price_range_min: 2500000,
    price_range_max: 8000000,
    average_price: 4800000,
    vat_inclusive: true,
    main_image_url: 'https://picsum.photos/seed/southpt/900/600',
    is_featured: false,
    project_amenities: [
      { amenities: { id: 1, name: 'Swimming Pool' } },
      { amenities: { id: 4, name: 'Playground' } },
      { amenities: { id: 5, name: 'Basketball Court' } },
      { amenities: { id: 7, name: 'Clubhouse' } },
      { amenities: { id: 10, name: '24/7 Security' } },
    ],
    project_galleries: [
      { id: 20, image_url: 'https://picsum.photos/seed/bac1/900/600', title: 'Development Overview', display_order: 0 },
      { id: 21, image_url: 'https://picsum.photos/seed/bac2/900/600', title: 'Model Unit', display_order: 1 },
    ],
    project_units: [
      { id: 19, unit_name: '2-Bedroom', unit_type: '2 Bedroom', floor_area_sqm: 48, bedrooms: 2, bathrooms: 1, has_balcony: true, has_parking: true, status: 'Available', selling_price: 2500000 },
      { id: 20, unit_name: '3-Bedroom', unit_type: '3 Bedroom', floor_area_sqm: 72, bedrooms: 3, bathrooms: 2, has_balcony: true, has_parking: true, status: 'Available', selling_price: 4800000 },
    ],
    faqs: [
      { id: 12, question: 'What makes Bacolod a good investment?', answer: 'Bacolod is the fastest-growing city outside Metro Manila with rising BPO activity, tourism, and a strong local economy.' },
    ],
  },
  {
    id: 8,
    uuid: 'proj-uuid-008',
    name: 'The Proscenium at Rockwell',
    slug: 'proscenium-rockwell',
    developer_id: 4,
    developers_profiles: { id: 4, developer_name: 'Federal Land Inc.', logo_url: 'https://picsum.photos/seed/federal/200/200' },
    project_type: 'High-Rise Condominium',
    classification: 'Luxury',
    region: 'NCR',
    province: 'Metro Manila',
    city_municipality: 'Makati City',
    barangay: 'Rockwell Center',
    island_group: 'Luzon',
    address_details: 'Rockwell Center, Makati City',
    latitude: 14.5649,
    longitude: 121.0359,
    status: 'Ready for Occupancy',
    currency: 'PHP',
    price_range_min: 15000000,
    price_range_max: 85000000,
    average_price: 38000000,
    vat_inclusive: true,
    main_image_url: 'https://picsum.photos/seed/proscen/900/600',
    is_featured: true,
    project_amenities: [
      { amenities: { id: 1, name: 'Swimming Pool' } },
      { amenities: { id: 2, name: 'Fitness Gym' } },
      { amenities: { id: 3, name: 'Covered Parking' } },
      { amenities: { id: 6, name: 'Tennis Court' } },
      { amenities: { id: 7, name: 'Clubhouse' } },
      { amenities: { id: 15, name: 'Yoga Studio' } },
      { amenities: { id: 17, name: 'Sky Lounge' } },
      { amenities: { id: 19, name: 'Concierge Service' } },
    ],
    project_galleries: [
      { id: 22, image_url: 'https://picsum.photos/seed/pro1/900/600', title: 'Tower Night View', display_order: 0 },
      { id: 23, image_url: 'https://picsum.photos/seed/pro2/900/600', title: 'Infinity Pool', display_order: 1 },
      { id: 24, image_url: 'https://picsum.photos/seed/pro3/900/600', title: 'Penthouse Living', display_order: 2 },
      { id: 25, image_url: 'https://picsum.photos/seed/pro4/900/600', title: 'Sky Lounge', display_order: 3 },
    ],
    project_units: [
      { id: 21, unit_name: '2-Bedroom', unit_type: '2 Bedroom', floor_area_sqm: 88, bedrooms: 2, bathrooms: 2, has_balcony: true, has_parking: true, status: 'Available', selling_price: 15000000 },
      { id: 22, unit_name: '3-Bedroom', unit_type: '3 Bedroom', floor_area_sqm: 140, bedrooms: 3, bathrooms: 3, has_balcony: true, has_parking: true, status: 'Available', selling_price: 32000000 },
      { id: 23, unit_name: 'Penthouse', unit_type: 'Penthouse', floor_area_sqm: 320, bedrooms: 4, bathrooms: 5, has_balcony: true, has_parking: true, status: 'Available', selling_price: 85000000 },
    ],
    faqs: [
      { id: 13, question: 'What makes Proscenium unique?', answer: 'Proscenium is the first-ever luxury arts-inspired development in the Philippines built around The Rockwell Club.' },
    ],
  },
  {
    id: 9,
    uuid: 'proj-uuid-009',
    name: 'Park Triangle Residences',
    slug: 'park-triangle-residences',
    developer_id: 1,
    developers_profiles: { id: 1, developer_name: 'Ayala Land Inc.', logo_url: 'https://picsum.photos/seed/ayala/200/200' },
    project_type: 'High-Rise Condominium',
    classification: 'Premium',
    region: 'NCR',
    province: 'Metro Manila',
    city_municipality: 'Taguig City',
    barangay: 'BGC',
    island_group: 'Luzon',
    address_details: 'Park Triangle, Bonifacio Global City, Taguig',
    latitude: 14.5505,
    longitude: 121.0513,
    status: 'Pre-Selling',
    currency: 'PHP',
    price_range_min: 9500000,
    price_range_max: 42000000,
    average_price: 21000000,
    vat_inclusive: true,
    main_image_url: 'https://picsum.photos/seed/parktri/900/600',
    is_featured: false,
    project_amenities: [
      { amenities: { id: 1, name: 'Swimming Pool' } },
      { amenities: { id: 2, name: 'Fitness Gym' } },
      { amenities: { id: 3, name: 'Covered Parking' } },
      { amenities: { id: 7, name: 'Clubhouse' } },
      { amenities: { id: 10, name: '24/7 Security' } },
      { amenities: { id: 17, name: 'Sky Lounge' } },
    ],
    project_galleries: [
      { id: 26, image_url: 'https://picsum.photos/seed/pt1/900/600', title: 'Building Exterior', display_order: 0 },
      { id: 27, image_url: 'https://picsum.photos/seed/pt2/900/600', title: 'Park View', display_order: 1 },
    ],
    project_units: [
      { id: 24, unit_name: '1-Bedroom', unit_type: '1 Bedroom', floor_area_sqm: 45, bedrooms: 1, bathrooms: 1, has_balcony: true, has_parking: true, status: 'Available', selling_price: 9500000 },
      { id: 25, unit_name: '2-Bedroom', unit_type: '2 Bedroom', floor_area_sqm: 72, bedrooms: 2, bathrooms: 2, has_balcony: true, has_parking: true, status: 'Available', selling_price: 18000000 },
    ],
    faqs: [],
  },
  {
    id: 10,
    uuid: 'proj-uuid-010',
    name: 'La Mirada de Sta. Rosa',
    slug: 'la-mirada-sta-rosa',
    developer_id: 7,
    developers_profiles: { id: 7, developer_name: 'Vista Land & Residences', logo_url: 'https://picsum.photos/seed/vistaland/200/200' },
    project_type: 'House & Lot',
    classification: 'Mid-Range',
    region: 'Region IV-A',
    province: 'Laguna',
    city_municipality: 'Sta. Rosa City',
    barangay: 'Don Jose',
    island_group: 'Luzon',
    address_details: 'Sta. Rosa-Tagaytay Road, Sta. Rosa, Laguna',
    latitude: 14.2812,
    longitude: 121.0997,
    status: 'Ready for Occupancy',
    currency: 'PHP',
    price_range_min: 3800000,
    price_range_max: 9500000,
    average_price: 6000000,
    vat_inclusive: true,
    main_image_url: 'https://picsum.photos/seed/lamirada/900/600',
    is_featured: false,
    project_amenities: [
      { amenities: { id: 1, name: 'Swimming Pool' } },
      { amenities: { id: 4, name: 'Playground' } },
      { amenities: { id: 5, name: 'Basketball Court' } },
      { amenities: { id: 7, name: 'Clubhouse' } },
      { amenities: { id: 10, name: '24/7 Security' } },
      { amenities: { id: 13, name: 'Jogging Path' } },
    ],
    project_galleries: [
      { id: 28, image_url: 'https://picsum.photos/seed/lam1/900/600', title: 'House Model', display_order: 0 },
      { id: 29, image_url: 'https://picsum.photos/seed/lam2/900/600', title: 'Community', display_order: 1 },
    ],
    project_units: [
      { id: 26, unit_name: 'Adriana', unit_type: '3-Bedroom House', floor_area_sqm: 72, lot_area_sqm: 120, bedrooms: 3, bathrooms: 2, has_parking: true, status: 'Available', selling_price: 3800000 },
      { id: 27, unit_name: 'Bianca', unit_type: '4-Bedroom House', floor_area_sqm: 110, lot_area_sqm: 180, bedrooms: 4, bathrooms: 3, has_parking: true, status: 'Available', selling_price: 7500000 },
    ],
    faqs: [
      { id: 14, question: 'How far is it from Tagaytay?', answer: 'La Mirada is approximately 20-25 minutes from Tagaytay City, making it ideal for weekend retreats.' },
    ],
  },
]

// ── Property Listings ────────────────────────────────────────────────────────
export const MOCK_LISTINGS = [
  {
    id: 101,
    user_profile_id: 'user-001',
    developer_id: 1,
    project_id: 1,
    project_unit_id: 2,
    title: '1-Bedroom Unit at One Serendra BGC',
    description: 'Thoughtfully designed 1-bedroom condominium unit on the 18th floor of One Serendra. Features premium finishes, floor-to-ceiling windows with stunning city views, modern fixtures, and a well-equipped kitchen. Ready for move-in.',
    listing_type: 'sale',
    status: 'published',
    currency: 'PHP',
    price: 12800000,
    negotiable: true,
    is_featured: true,
    views_count: 342,
    inquiries_count: 14,
    projects: { id: 1, name: 'One Serendra', slug: 'one-serendra', city_municipality: 'Taguig City', province: 'Metro Manila' },
    developers_profiles: { developer_name: 'Ayala Land Inc.' },
    project_units: { bedrooms: 1, bathrooms: 1, floor_area_sqm: 42, is_rfo: true, is_furnished: 'Semi-Furnished' },
    property_listing_galleries: [
      { image_url: 'https://picsum.photos/seed/list101a/900/600', display_order: 0 },
      { image_url: 'https://picsum.photos/seed/list101b/900/600', display_order: 1 },
      { image_url: 'https://picsum.photos/seed/list101c/900/600', display_order: 2 },
    ],
  },
  {
    id: 102,
    user_profile_id: 'user-001',
    developer_id: 1,
    project_id: 1,
    project_unit_id: 3,
    title: 'Spacious 2BR Unit at One Serendra – City Views',
    description: 'Enjoy panoramic views of BGC from this elegant 2-bedroom unit on the 24th floor. Open-plan living and dining, master bedroom with en-suite bath, and a private balcony perfect for sunsets.',
    listing_type: 'sale',
    status: 'published',
    currency: 'PHP',
    price: 18500000,
    negotiable: false,
    is_featured: true,
    views_count: 198,
    inquiries_count: 9,
    projects: { id: 1, name: 'One Serendra', slug: 'one-serendra', city_municipality: 'Taguig City', province: 'Metro Manila' },
    developers_profiles: { developer_name: 'Ayala Land Inc.' },
    project_units: { bedrooms: 2, bathrooms: 2, floor_area_sqm: 68, is_rfo: true, is_furnished: 'Semi-Furnished' },
    property_listing_galleries: [
      { image_url: 'https://picsum.photos/seed/list102a/900/600', display_order: 0 },
      { image_url: 'https://picsum.photos/seed/list102b/900/600', display_order: 1 },
    ],
  },
  {
    id: 103,
    user_profile_id: 'user-002',
    developer_id: 2,
    project_id: 2,
    project_unit_id: 6,
    title: 'Brand New 1BR Unit for Rent – Breeze MOA',
    description: 'Newly furnished 1-bedroom unit at Breeze Residences, just minutes from SM Mall of Asia. Modern kitchen, combined living-dining area, and city views. Includes parking slot. All-in rent.',
    listing_type: 'rent',
    status: 'published',
    currency: 'PHP',
    price: 35000,
    negotiable: true,
    is_featured: false,
    views_count: 156,
    inquiries_count: 7,
    projects: { id: 2, name: 'Breeze Residences', slug: 'breeze-residences', city_municipality: 'Pasay City', province: 'Metro Manila' },
    developers_profiles: { developer_name: 'SM Prime Holdings' },
    project_units: { bedrooms: 1, bathrooms: 1, floor_area_sqm: 38, is_rfo: true, is_furnished: 'Fully Furnished' },
    property_listing_galleries: [
      { image_url: 'https://picsum.photos/seed/list103a/900/600', display_order: 0 },
      { image_url: 'https://picsum.photos/seed/list103b/900/600', display_order: 1 },
    ],
  },
  {
    id: 104,
    user_profile_id: 'user-003',
    developer_id: 3,
    project_id: 3,
    project_unit_id: 9,
    title: '1-Bedroom Condo for Sale – Galleria Residences Cebu',
    description: 'Well-maintained 1-bedroom unit at Galleria Residences, in the heart of Cebu Business Park. Walking distance to Ayala Center, major offices, and restaurants. Semi-furnished with aircon units included.',
    listing_type: 'sale',
    status: 'published',
    currency: 'PHP',
    price: 8200000,
    negotiable: true,
    is_featured: false,
    views_count: 88,
    inquiries_count: 5,
    projects: { id: 3, name: 'Galleria Residences', slug: 'galleria-residences', city_municipality: 'Cebu City', province: 'Cebu' },
    developers_profiles: { developer_name: 'Robinsons Land Corp' },
    project_units: { bedrooms: 1, bathrooms: 1, floor_area_sqm: 40, is_rfo: true, is_furnished: 'Semi-Furnished' },
    property_listing_galleries: [
      { image_url: 'https://picsum.photos/seed/list104a/900/600', display_order: 0 },
      { image_url: 'https://picsum.photos/seed/list104b/900/600', display_order: 1 },
    ],
  },
  {
    id: 105,
    user_profile_id: 'user-004',
    developer_id: 7,
    project_id: 4,
    project_unit_id: 12,
    title: "3-Bedroom House & Lot – Camella Daang Hari, Cavite",
    description: 'Ready-for-occupancy house in Camella Daang Hari. Three bedrooms, 2 bathrooms, covered carport, manicured yard, and access to all subdivision amenities. Perfect for growing families.',
    listing_type: 'sale',
    status: 'published',
    currency: 'PHP',
    price: 4800000,
    negotiable: false,
    is_featured: true,
    views_count: 267,
    inquiries_count: 18,
    projects: { id: 4, name: 'Camella Daang Hari', slug: 'camella-daang-hari', city_municipality: 'Bacoor', province: 'Cavite' },
    developers_profiles: { developer_name: 'Vista Land & Residences' },
    project_units: { bedrooms: 3, bathrooms: 2, floor_area_sqm: 64, lot_area_sqm: 132, is_rfo: true, is_furnished: 'Unfurnished' },
    property_listing_galleries: [
      { image_url: 'https://picsum.photos/seed/list105a/900/600', display_order: 0 },
      { image_url: 'https://picsum.photos/seed/list105b/900/600', display_order: 1 },
      { image_url: 'https://picsum.photos/seed/list105c/900/600', display_order: 2 },
    ],
  },
  {
    id: 106,
    user_profile_id: 'user-005',
    developer_id: 5,
    project_id: 5,
    project_unit_id: 14,
    title: '1BR Condo for Rent – Satori Residences Pasig',
    description: 'Fully furnished 1-bedroom at Satori Residences, DMCI resort-style living along EDSA. Lush landscaping, pool access, gym. Unit includes inverter aircon, refrigerator, washing machine. Monthly includes building dues.',
    listing_type: 'rent',
    status: 'published',
    currency: 'PHP',
    price: 28000,
    negotiable: false,
    is_featured: false,
    views_count: 124,
    inquiries_count: 6,
    projects: { id: 5, name: 'Satori Residences', slug: 'satori-residences', city_municipality: 'Pasig City', province: 'Metro Manila' },
    developers_profiles: { developer_name: 'DMCI Homes' },
    project_units: { bedrooms: 1, bathrooms: 1, floor_area_sqm: 41, is_rfo: true, is_furnished: 'Fully Furnished' },
    property_listing_galleries: [
      { image_url: 'https://picsum.photos/seed/list106a/900/600', display_order: 0 },
      { image_url: 'https://picsum.photos/seed/list106b/900/600', display_order: 1 },
    ],
  },
  {
    id: 107,
    user_profile_id: 'user-006',
    developer_id: 6,
    project_id: 6,
    project_unit_id: 17,
    title: '1BR Unit at Iloilo Business Park – For Rent',
    description: 'Airbnb-ready 1-bedroom unit in Megaworld\'s Iloilo Business Park. Walk to Festive Walk Mall and all I.T.-BPO offices. Modern furnishings, full-size bed, cable TV, fast internet. Great investment.',
    listing_type: 'rent',
    status: 'published',
    currency: 'PHP',
    price: 22000,
    negotiable: true,
    is_featured: true,
    views_count: 191,
    inquiries_count: 12,
    projects: { id: 6, name: 'Iloilo Business Park Richmonde Tower', slug: 'iloilo-business-park-richmonde', city_municipality: 'Mandurriao', province: 'Iloilo' },
    developers_profiles: { developer_name: 'Megaworld Corp' },
    project_units: { bedrooms: 1, bathrooms: 1, floor_area_sqm: 39, is_rfo: true, is_furnished: 'Fully Furnished' },
    property_listing_galleries: [
      { image_url: 'https://picsum.photos/seed/list107a/900/600', display_order: 0 },
      { image_url: 'https://picsum.photos/seed/list107b/900/600', display_order: 1 },
    ],
  },
  {
    id: 108,
    user_profile_id: 'user-007',
    developer_id: 4,
    project_id: 8,
    project_unit_id: 21,
    title: 'Luxury 2-Bedroom at The Proscenium – Makati',
    description: 'Rarely available 2-bedroom unit at The Proscenium at Rockwell. The epitome of luxury living: Italian marble flooring, Poggenpohl kitchen cabinetry, Grohe and Villeroy & Boch fixtures. Access to The Rockwell Club.',
    listing_type: 'sale',
    status: 'published',
    currency: 'PHP',
    price: 18500000,
    negotiable: false,
    is_featured: true,
    views_count: 445,
    inquiries_count: 22,
    projects: { id: 8, name: 'The Proscenium at Rockwell', slug: 'proscenium-rockwell', city_municipality: 'Makati City', province: 'Metro Manila' },
    developers_profiles: { developer_name: 'Federal Land Inc.' },
    project_units: { bedrooms: 2, bathrooms: 2, floor_area_sqm: 88, is_rfo: true, is_furnished: 'Fully Furnished' },
    property_listing_galleries: [
      { image_url: 'https://picsum.photos/seed/list108a/900/600', display_order: 0 },
      { image_url: 'https://picsum.photos/seed/list108b/900/600', display_order: 1 },
      { image_url: 'https://picsum.photos/seed/list108c/900/600', display_order: 2 },
      { image_url: 'https://picsum.photos/seed/list108d/900/600', display_order: 3 },
    ],
  },
  {
    id: 109,
    user_profile_id: 'user-008',
    developer_id: 8,
    project_id: 7,
    project_unit_id: 20,
    title: '3BR Condo for Sale – Southpoint Bacolod',
    description: 'Spacious 3-bedroom unit at Southpoint, Bacolod City\'s newest integrated development. Modern finishes, open-plan kitchen, mountain views. Ideal for families relocating to Bacolod. Pre-selling price guaranteed.',
    listing_type: 'sale',
    status: 'published',
    currency: 'PHP',
    price: 4500000,
    negotiable: true,
    is_featured: false,
    views_count: 76,
    inquiries_count: 4,
    projects: { id: 7, name: 'Southpoint Bacolod', slug: 'southpoint-bacolod', city_municipality: 'Bacolod City', province: 'Bacolod' },
    developers_profiles: { developer_name: 'Filinvest Land' },
    project_units: { bedrooms: 3, bathrooms: 2, floor_area_sqm: 72, is_rfo: false, is_furnished: 'Unfurnished' },
    property_listing_galleries: [
      { image_url: 'https://picsum.photos/seed/list109a/900/600', display_order: 0 },
    ],
  },
  {
    id: 110,
    user_profile_id: 'user-009',
    developer_id: 7,
    project_id: 10,
    project_unit_id: 26,
    title: '3BR House & Lot at La Mirada – Sta. Rosa Laguna',
    description: 'Elegant 3-bedroom home in the master-planned community of La Mirada de Sta. Rosa. Spacious 120sqm lot, 2 covered parking spaces, and access to a private pool and clubhouse. Near Tagaytay and SLEX.',
    listing_type: 'sale',
    status: 'published',
    currency: 'PHP',
    price: 4200000,
    negotiable: false,
    is_featured: false,
    views_count: 93,
    inquiries_count: 6,
    projects: { id: 10, name: 'La Mirada de Sta. Rosa', slug: 'la-mirada-sta-rosa', city_municipality: 'Sta. Rosa City', province: 'Laguna' },
    developers_profiles: { developer_name: 'Vista Land & Residences' },
    project_units: { bedrooms: 3, bathrooms: 2, floor_area_sqm: 72, lot_area_sqm: 120, is_rfo: true, is_furnished: 'Unfurnished' },
    property_listing_galleries: [
      { image_url: 'https://picsum.photos/seed/list110a/900/600', display_order: 0 },
      { image_url: 'https://picsum.photos/seed/list110b/900/600', display_order: 1 },
    ],
  },
  {
    id: 111,
    user_profile_id: 'user-010',
    developer_id: 1,
    project_id: 9,
    project_unit_id: 24,
    title: '1BR at Park Triangle Residences – BGC Pre-Selling',
    description: 'Park-facing 1-bedroom unit at the new Park Triangle Residences in BGC. Floor-to-ceiling windows offer direct views of the park. High-spec finishes across all surfaces. Competitive pre-selling price with favorable payment schemes.',
    listing_type: 'sale',
    status: 'published',
    currency: 'PHP',
    price: 9800000,
    negotiable: false,
    is_featured: false,
    views_count: 211,
    inquiries_count: 10,
    projects: { id: 9, name: 'Park Triangle Residences', slug: 'park-triangle-residences', city_municipality: 'Taguig City', province: 'Metro Manila' },
    developers_profiles: { developer_name: 'Ayala Land Inc.' },
    project_units: { bedrooms: 1, bathrooms: 1, floor_area_sqm: 45, is_rfo: false, is_furnished: 'Unfurnished' },
    property_listing_galleries: [
      { image_url: 'https://picsum.photos/seed/list111a/900/600', display_order: 0 },
      { image_url: 'https://picsum.photos/seed/list111b/900/600', display_order: 1 },
    ],
  },
  {
    id: 112,
    user_profile_id: 'user-011',
    developer_id: 2,
    project_id: 2,
    project_unit_id: 5,
    title: 'Studio for Rent – Breeze MOA Near Airport',
    description: 'Compact and cozy studio unit at Breeze Residences. Functional layout with built-in closets, study nook, and kitchen pantry. Walking distance to MOA Arena and SM Mall of Asia. Perfect for young professionals.',
    listing_type: 'rent',
    status: 'published',
    currency: 'PHP',
    price: 20000,
    negotiable: true,
    is_featured: false,
    views_count: 105,
    inquiries_count: 5,
    projects: { id: 2, name: 'Breeze Residences', slug: 'breeze-residences', city_municipality: 'Pasay City', province: 'Metro Manila' },
    developers_profiles: { developer_name: 'SM Prime Holdings' },
    project_units: { bedrooms: 0, bathrooms: 1, floor_area_sqm: 24, is_rfo: true, is_furnished: 'Semi-Furnished' },
    property_listing_galleries: [
      { image_url: 'https://picsum.photos/seed/list112a/900/600', display_order: 0 },
    ],
  },
]

// ── Site Locations ───────────────────────────────────────────────────────────
export const MOCK_LOCATIONS = [
  { id: 1, title: 'Cebu', slug: 'cebu', description: 'The Queen City of the South', logo_url: null, is_active: true },
  { id: 2, title: 'BGC', slug: 'bgc', description: 'Bonifacio Global City – Modern urban living', logo_url: null, is_active: true },
  { id: 3, title: 'Cavite', slug: 'cavite', description: 'Gateway to South Luzon', logo_url: null, is_active: true },
  { id: 4, title: 'Bacolod', slug: 'bacolod', description: 'City of Smiles', logo_url: null, is_active: true },
  { id: 5, title: 'Bohol', slug: 'bohol', description: 'Nature and tranquility', logo_url: null, is_active: true },
  { id: 6, title: 'Iloilo', slug: 'iloilo', description: 'The Biggest Little City in the Philippines', logo_url: null, is_active: true },
  { id: 7, title: 'Cagayan de Oro', slug: 'cagayan-de-oro', description: 'City of Golden Friendship', logo_url: null, is_active: true },
  { id: 8, title: 'Davao', slug: 'davao', description: "The Philippines' safest city", logo_url: null, is_active: true },
  { id: 9, title: 'General Santos', slug: 'gensan', description: 'Tuna Capital of the Philippines', logo_url: null, is_active: true },
  { id: 10, title: 'Pampanga', slug: 'pampanga', description: 'The Culinary Capital of the Philippines', logo_url: null, is_active: true },
]

// ── News Articles ────────────────────────────────────────────────────────────
export const MOCK_NEWS = [
  {
    id: 1,
    slug: 'philippine-real-estate-booming-2026',
    title: 'Philippine Real Estate Market Sees Strongest Growth in a Decade',
    excerpt: 'New data from the Bangko Sentral ng Pilipinas confirms that residential property values increased by 12.4% year-on-year in Q1 2026, driven by foreign investment and OFW remittances.',
    content: 'Full article content here...',
    category: 'Market Trends',
    image_url: 'https://picsum.photos/seed/news1/800/500',
    author: 'Maria Santos',
    published_at: '2026-03-10',
    read_time: 5,
    tags: ['Market Trends', 'Investment', 'BGC', 'Cebu'],
  },
  {
    id: 101,
    title: 'Philippine Real Estate Market Sees Strongest Growth in a Decade',
    slug: 'philippine-real-estate-market-growth',
    category: 'Market Trends',
    image_url: 'https://picsum.photos/seed/news1/800/500',
    excerpt: 'The Philippine real estate market witnessed a record-breaking surge in housing demand, driven largely by returning OFWs and low-interest rates.',
    published_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 118,
    title: 'BGC Commercial Growth to Accelerate in 2026',
    slug: 'bgc-commercial-growth-2026',
    category: 'New Developments',
    image_url: 'https://picsum.photos/seed/news2/800/500',
    excerpt: 'Bonifacio Global City is set to see a new wave of commercial development projects this year attracting international investors.',
    published_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 119,
    title: 'Investors Flocking to Metro Manila Condos',
    slug: 'investors-metro-manila-condos',
    category: 'Regional Update',
    image_url: 'https://picsum.photos/seed/news3/800/500',
    excerpt: 'The metro condo market is heating up as foreign investors seek long-term rental yields in key urban locations.',
    published_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 120,
    title: 'Sustainability Takes Center Stage in New Developments',
    slug: 'sustainability-new-developments',
    category: 'Sustainability',
    image_url: 'https://picsum.photos/seed/news4/800/500',
    excerpt: 'Developers are integrating green building practices in upcoming projects across the country.',
    published_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 121,
    title: 'Affordable Housing Initiatives Gain Momentum',
    slug: 'affordable-housing-initiatives',
    category: 'Market Trends',
    image_url: 'https://picsum.photos/seed/news5/800/500',
    excerpt: 'Government programs aim to improve access to affordable housing in urban and rural areas.',
    published_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 122,
    title: 'The Rise of Mixed-Use Developments in the Philippines',
    slug: 'mixed-use-developments',
    category: 'New Developments',
    image_url: 'https://picsum.photos/seed/news6/800/500',
    excerpt: 'Mixed-use projects are reshaping the urban landscape with integrated commercial and residential spaces.',
    published_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 123,
    title: 'Trends in Regional Real Estate Markets',
    slug: 'regional-real-estate-trends',
    category: 'Regional Update',
    image_url: 'https://picsum.photos/seed/news7/800/500',
    excerpt: 'Regional markets are seeing increased demand driven by local business expansions and infrastructure developments.',
    published_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 124,
    title: 'Investing in Rental Properties: What You Need to Know',
    slug: 'investing-rental-properties',
    category: 'Investment',
    image_url: 'https://picsum.photos/seed/news8/800/500',
    excerpt: 'A detailed guide on the advantages and risks of investing in rental properties across the country.',
    published_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 125,
    title: 'Commercial Spaces Seeing Higher Demand in Metro Manila',
    slug: 'commercial-space-demand',
    category: 'Market Trends',
    image_url: 'https://picsum.photos/seed/news9/800/500',
    excerpt: 'Metro Manila\'s business district is experiencing increased interest in commercial real estate.',
    published_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 126,
    title: 'New Condo Developments in BGC and Makati',
    slug: 'new-condo-developments-bgc-makati',
    category: 'New Developments',
    image_url: 'https://picsum.photos/seed/news10/800/500',
    excerpt: 'Several high-profile condo projects are underway in key business districts.',
    published_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 127,
    title: 'Real Estate Market Recovery Post-Pandemic',
    slug: 'real-estate-market-recovery',
    category: 'Market Trends',
    image_url: 'https://picsum.photos/seed/news11/800/500',
    excerpt: 'The real estate market is showing signs of recovery after the pandemic slowdown.',
    published_at: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 128,
    title: 'Analyzing Real Estate Price Trends in 2026',
    slug: 'real-estate-price-trends-2026',
    category: 'Investment',
    image_url: 'https://picsum.photos/seed/news12/800/500',
    excerpt: 'Experts provide insights into price fluctuations in the real estate market this year.',
    published_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 129,
    title: 'BGC and Makati Lead in New Condo Launches',
    slug: 'bgc-makati-condo-launches',
    category: 'New Developments',
    image_url: 'https://picsum.photos/seed/news13/800/500',
    excerpt: 'The business districts of BGC and Makati continue to attract major developers with a flurry of new condo projects.',
    published_at: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    slug: 'cebu-condo-demand-rise',
    title: 'Cebu City Condo Demand Surges as BPO Sector Expands',
    excerpt: 'Driven by a 22% increase in BPO employment and returning OFWs, demand for mid-range condominiums in Cebu City hit an all-time high last quarter.',
    content: 'Full article...',
    category: 'Regional Update',
    image_url: 'https://picsum.photos/seed/news3/800/500',
    author: 'Ana Lim',
    published_at: '2026-03-05',
    read_time: 6,
    tags: ['Cebu', 'BPO', 'Condominiums'],
  },
  {
    id: 4,
    slug: 'iloilo-rising-investment',
    title: 'Iloilo Named Among Top Investment Destinations in SEA for 2026',
    excerpt: 'An Asean business intelligence report ranked Iloilo in the top 10 second-tier cities for real estate investment in Southeast Asia, citing infrastructure growth and quality of life.',
    content: 'Full article...',
    category: 'Investment',
    image_url: 'https://picsum.photos/seed/news4/800/500',
    author: 'Elena Villanueva',
    published_at: '2026-03-02',
    read_time: 5,
    tags: ['Iloilo', 'Investment', 'Southeast Asia'],
  },
  {
    id: 5,
    slug: 'green-buildings-ph',
    title: 'Green-Certified Condos Command 18% Premium in Metro Manila',
    excerpt: 'Sustainability sells: LEED and BERDE-certified residential buildings in Metro Manila are selling 18% higher than comparable non-certified units, with demand outpacing supply.',
    content: 'Full article...',
    category: 'Sustainability',
    image_url: 'https://picsum.photos/seed/news5/800/500',
    author: 'Grace Mendoza',
    published_at: '2026-02-28',
    read_time: 7,
    tags: ['Sustainability', 'Green Buildings', 'Metro Manila'],
  },
  {
    id: 6,
    slug: 'ofw-real-estate-guide',
    title: 'The Complete Guide for OFWs Buying Property in the Philippines',
    excerpt: 'Everything an overseas Filipino worker needs to know about purchasing property back home — from financing options and legal requirements to the latest project opportunities.',
    content: 'Full article...',
    category: 'Guides',
    image_url: 'https://picsum.photos/seed/news6/800/500',
    author: 'Roberto Garcia',
    published_at: '2026-02-25',
    read_time: 10,
    tags: ['OFW', 'Guide', 'Financing'],
  },
]

// ── Tourism Destinations ─────────────────────────────────────────────────────
export const MOCK_TOURISM = [
  {
    id: 301,
    location: 'Cebu',
    name: 'Kawasan Falls',
    description: 'Multi-tiered turquoise waterfalls set in the lush mountains of Badian, Cebu. A canyoneering adventure paradise.',
    type: 'Nature',
    image_url: 'https://picsum.photos/seed/kawasan/800/500',
    tags: ['Nature', 'Adventure', 'Waterfalls'],
    published_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 302,
    location: 'Bohol',
    name: 'Chocolate Hills',
    description: 'Over 1,200 dome-shaped hills that turn brown in summer — one of the Philippines\' most iconic landscapes and a UNESCO tentative heritage site.',
    type: 'Nature',
    image_url: 'https://picsum.photos/seed/boholhills/800/500',
    tags: ['Nature', 'UNESCO', 'Landmark'],
    published_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 303,
    location: 'Palawan',
    name: 'El Nido Island Hopping',
    description: 'Dramatic limestone karst formations, hidden lagoons, and pristine white-sand beaches — El Nido is consistently rated among the world\'s best islands.',
    type: 'Beach',
    image_url: 'https://picsum.photos/seed/elnido/800/500',
    tags: ['Beach', 'Adventure', 'World-Class'],
    published_at: new Date(Date.now() - 0 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 304,
    location: 'BGC',
    name: 'Bonifacio High Street',
    description: 'Upscale open-air retail and dining strip in the heart of BGC. Home to international brands, art installations, and the best dining in Metro Manila.',
    type: 'Urban',
    image_url: 'https://picsum.photos/seed/bhs/800/500',
    tags: ['Urban', 'Dining', 'Shopping'],
    published_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 305,
    location: 'Davao',
    name: 'Mount Apo Climb',
    description: 'The highest peak in the Philippines at 2,954 meters above sea level. A challenging multi-day trek through diverse ecosystems.',
    type: 'Adventure',
    image_url: 'https://picsum.photos/seed/mountapo/800/500',
    tags: ['Adventure', 'Hiking', 'Landmark'],
    published_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 306,
    location: 'Iloilo',
    name: 'Miag-ao Church',
    description: 'A UNESCO World Heritage Site featuring a stunning Baroque-style facade built in 1786. A symbol of Iloilo\'s rich cultural heritage.',
    type: 'Heritage',
    image_url: 'https://picsum.photos/seed/miagao/800/500',
    tags: ['Heritage', 'Cultural'],
    published_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 307,
    location: 'Batangas',
    name: 'Taal Volcano and Lake',
    description: 'One of the world\'s most picturesque volcanic landscapes with scenic lake views and hiking trails suitable for all skill levels.',
    type: 'Nature',
    image_url: 'https://picsum.photos/seed/taal/800/500',
    tags: ['Nature', 'Volcano', 'Hiking'],
    published_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 308,
    location: 'Aklan',
    name: 'Boracay Island Beach Resort',
    description: 'A world-famous tropical island destination known for pristine white-sand beaches, water sports, and vibrant beach resorts.',
    type: 'Beach',
    image_url: 'https://picsum.photos/seed/boracay/800/500',
    tags: ['Beach', 'Resort', 'Water Sports'],
    published_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 309,
    location: 'Negros Occidental',
    name: 'Sipalay Sunset Beach',
    description: 'A hidden gem featuring powdery black and white sand beaches with some of the most stunning sunsets in the Philippines.',
    type: 'Beach',
    image_url: 'https://picsum.photos/seed/sipalay/800/500',
    tags: ['Beach', 'Sunset', 'Hidden'],
    published_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 310,
    location: 'Manila',
    name: 'Fort Santiago Historic Site',
    description: 'A 16th-century Spanish colonial fortress offering insights into Philippine history with museums, gardens, and cultural exhibits.',
    type: 'Heritage',
    image_url: 'https://picsum.photos/seed/fortsantiago/800/500',
    tags: ['Heritage', 'History', 'Museum'],
    published_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 311,
    location: 'Ilocos Sur',
    name: 'Vigan Heritage City',
    description: 'A UNESCO-listed city with well-preserved Spanish colonial architecture, cobblestone streets, and charming historical buildings.',
    type: 'Heritage',
    image_url: 'https://picsum.photos/seed/vigan/800/500',
    tags: ['Heritage', 'UNESCO', 'History'],
    published_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 312,
    location: 'Palawan',
    name: 'Tubbataha Reef National Marine Park',
    description: 'An underwater paradise featuring pristine coral reefs, diverse marine life, and world-class diving opportunities.',
    type: 'Nature',
    image_url: 'https://picsum.photos/seed/tubbataha/800/500',
    tags: ['Nature', 'Reef', 'Diving'],
    published_at: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 313,
    location: 'Laguna',
    name: 'Sagano Bamboo Grove Recreation',
    description: 'A serene bamboo forest offering peaceful walks, photography opportunities, and a unique natural retreat experience.',
    type: 'Nature',
    image_url: 'https://picsum.photos/seed/sagano/800/500',
    tags: ['Nature', 'Bamboo', 'Forest'],
    published_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 6,
    location: 'Iloilo',
    name: 'Miag-ao Church',
    description: 'A UNESCO World Heritage Site featuring a stunning Baroque-style facade, built in 1786 by Augustinian friars. A symbol of Iloilo\'s rich cultural heritage.',
    type: 'Heritage',
    image_url: 'https://picsum.photos/seed/tour6/800/500',
    tags: ['Heritage', 'UNESCO', 'History'],
    published_at: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
  }
]

// ── Restaurants ─────────────────────────────────────────────────────────────
export const MOCK_RESTAURANTS = [
  {
    id: 1,
    name: 'VASK Modern Tapas',
    location: 'BGC, Taguig',
    cuisine: 'Spanish-Filipino Fusion',
    description: 'Award-winning restaurant by Chef Jose Luis "Chele" Gonzalez. Innovative dishes combining Basque culinary techniques with the finest local ingredients.',
    price_range: '₱₱₱₱',
    rating: 4.9,
    image_url: 'https://picsum.photos/seed/resto1/800/500',
    tags: ['Fine Dining', 'Spanish', 'Award-Winning'],
    hours: 'Tue–Sun: 12pm–3pm, 6pm–10pm',
    phone: '+63 917 700 8275',
  },
  {
    id: 2,
    name: 'Cebu Lechon by Zubuchon',
    location: 'Cebu City, Cebu',
    cuisine: 'Filipino',
    description: 'Anthony Bourdain called it "the best pig I\'ve ever had." Zubuchon\'s iconic crispy whole roasted pig is a Cebu gastronomic institution.',
    price_range: '₱₱',
    rating: 4.8,
    image_url: 'https://picsum.photos/seed/resto2/800/500',
    tags: ['Filipino', 'Lechon', 'Iconic'],
    hours: 'Daily: 9am–8pm',
    phone: '+63 32 231 8865',
  },
  {
    id: 3,
    name: 'Breakthrough Seafood',
    location: 'Iloilo City, Iloilo',
    cuisine: 'Ilonggo Seafood',
    description: 'Famous for fresh seafood and traditional Ilonggo cuisine, Breakthrough has been serving the best kinilaw, grilled fish, and seafood platters since 1987.',
    price_range: '₱₱',
    rating: 4.7,
    image_url: 'https://picsum.photos/seed/resto3/800/500',
    tags: ['Seafood', 'Ilonggo', 'Traditional'],
    hours: 'Daily: 10am–9pm',
    phone: '+63 33 337 3797',
  },
  {
    id: 4,
    name: 'Claude\'s Le Café de Ville',
    location: 'Makati City, Metro Manila',
    cuisine: 'French-Filipino',
    description: 'A landmark of Manila fine dining where French culinary tradition meets Filipino warmth. Exceptional tasting menus paired with an extensive wine cellar.',
    price_range: '₱₱₱₱',
    rating: 4.8,
    image_url: 'https://picsum.photos/seed/resto4/800/500',
    tags: ['Fine Dining', 'French', 'Tasting Menu'],
    hours: 'Mon–Sat: 12pm–2:30pm, 7pm–10:30pm',
    phone: '+63 2 8892 2888',
  },
  {
    id: 5,
    name: 'Café Laguna',
    location: 'Bacolod City, Bacolod',
    cuisine: 'Negrosanon Filipino',
    description: 'Celebrating the best of Negrense cuisine — chicken inasal, kansi, and fresh seafood from Negros Occidental. A beloved institution since 1992.',
    price_range: '₱₱',
    rating: 4.6,
    image_url: 'https://picsum.photos/seed/resto5/800/500',
    tags: ['Filipino', 'Negrosanon', 'Traditional'],
    hours: 'Daily: 10am–9pm',
    phone: '+63 34 432 5678',
  },
  {
    id: 6,
    name: 'Seda Nourish',
    location: 'Davao City, Davao',
    cuisine: 'Modern Filipino',
    description: 'Located atop Seda Abreeza Hotel, offering panoramic city views and innovative dishes that highlight Mindanao\'s exceptional produce and seafood.',
    price_range: '₱₱₱',
    rating: 4.7,
    image_url: 'https://picsum.photos/seed/resto6/800/500',
    tags: ['Hotel Dining', 'Modern Filipino', 'City Views'],
    hours: 'Daily: 6:30am–10:30pm',
    phone: '+63 82 228 5733',
  },
]

// ── Mortgage Calculator Rates ────────────────────────────────────────────────
export const MORTGAGE_RATES = {
  bank_rates: [
    { bank: 'BDO Unibank', rate_1yr: 6.75, rate_5yr: 7.25, rate_10yr: 7.75, rate_20yr: 8.25 },
    { bank: 'BPI (Bank of the Philippine Islands)', rate_1yr: 6.50, rate_5yr: 7.00, rate_10yr: 7.50, rate_20yr: 8.00 },
    { bank: 'Metrobank', rate_1yr: 6.88, rate_5yr: 7.38, rate_10yr: 7.88, rate_20yr: 8.38 },
    { bank: 'Security Bank', rate_1yr: 6.63, rate_5yr: 7.13, rate_10yr: 7.63, rate_20yr: 8.13 },
    { bank: 'RCBC', rate_1yr: 7.00, rate_5yr: 7.50, rate_10yr: 8.00, rate_20yr: 8.50 },
    { bank: 'Pag-IBIG Fund', rate_1yr: 5.75, rate_5yr: 6.25, rate_10yr: 6.75, rate_20yr: 7.00 },
  ],
  pag_ibig_info: {
    max_loan: 6500000,
    max_repayment_period: 30,
    min_contribution_period: 24,
  },
}

// ── Site Stats ───────────────────────────────────────────────────────────────
export const SITE_STATS = {
  total_listings: 48000,
  total_projects: 1200,
  total_developers: 380,
  total_locations: 82,
  total_agents: 10500,
  total_buyers_served: 125000,
}

export type MockListing = typeof MOCK_LISTINGS[number]
export type MockProject = typeof MOCK_PROJECTS[number]
export type MockDeveloper = typeof MOCK_DEVELOPERS[number]
// Additional news mocks
export const MOCK_REAL_ESTATE_NEWS = [
  {
    id: 101,
    title: 'Canadian Visa Update to Foster Approvals - But What About Filipinos?',
    slug: 'canadian-visa-update-foster',
    category: 'Market Trends',
    image_url: 'https://picsum.photos/seed/realestate1/800/500',
    excerpt: 'Recent policy changes in Canada visa processing could impact Filipino investment migrants...',
    published_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 102,
    title: 'BGC Set to Welcome 3 New High-Rise Towers in 2026–2027',
    slug: 'bgc-new-developments',
    category: 'New Developments',
    image_url: 'https://picsum.photos/seed/realestate2/800/500',
    excerpt: 'Bonifacio Global City will see a wave of new residential towers breaking ground this year...',
    published_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 103,
    title: 'Cebu City Condo Demand Surges as BPO Sector Expands',
    slug: 'cebu-condo-demand',
    category: 'Regional Update',
    image_url: 'https://picsum.photos/seed/realestate3/800/500',
    excerpt: 'Driven by a 22% increase in BPO employment and returning OFWs, demand for condos is at an all-time high...',
    published_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 104,
    title: 'Iloilo Named Among Top Investment Destinations in SEA for 2026',
    slug: 'iloilo-investment-destination',
    category: 'Investment',
    image_url: 'https://picsum.photos/seed/realestate4/800/500',
    excerpt: 'An ASEAN report ranked Iloilo in the top 10 second-tier cities for real estate investment...',
    published_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 105,
    title: 'Green-Certified Condos Command 18% Premium in Metro Manila',
    slug: 'green-condos-premium',
    category: 'Sustainability',
    image_url: 'https://picsum.photos/seed/realestate5/800/500',
    excerpt: 'LEED and BERDE-certified residential buildings are selling 18% higher than comparable non-certified units...',
    published_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 106,
    title: 'Makati Skyline 2026: Top Commercial Developments Reshaping the District',
    slug: 'makati-skyline-2026',
    category: 'New Developments',
    image_url: 'https://picsum.photos/seed/realestate6/800/500',
    excerpt: 'Five major office and mixed-use towers are expected to complete in Makati by year-end...',
    published_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 107,
    title: 'Laguna Province Becomes the New BPO Hub: Real Estate Boom Incoming',
    slug: 'laguna-bpo-hub',
    category: 'Regional Update',
    image_url: 'https://picsum.photos/seed/realestate7/800/500',
    excerpt: 'With four new BPO centers opening in Laguna, property demand is expected to surge 40% this year...',
    published_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 108,
    title: 'Financing Real Estate in 2026: Banks Roll Out Flexible Payment Terms',
    slug: 'real-estate-financing-2026',
    category: 'Investment',
    image_url: 'https://picsum.photos/seed/realestate8/800/500',
    excerpt: 'Major banks and development companies announce eased financing schemes to boost property market...',
    published_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 109,
    title: 'Sustainable Living Trends: What Filipino Developers Are Building Today',
    slug: 'sustainable-living-trends',
    category: 'Sustainability',
    image_url: 'https://picsum.photos/seed/realestate9/800/500',
    excerpt: 'From rooftop farms to solar panels, developers are embracing eco-friendly features across the country...',
    published_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 110,
    title: 'Makati East Expansion: A New Skyline on the Horizon',
    slug: 'makati-east-expansion',
    category: 'New Developments',
    image_url: 'https://picsum.photos/seed/realestate1/800/500',
    excerpt: 'A major urban development project is transforming the eastern side of Makati into a modern mixed-use district...',
    published_at: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 111,
    title: 'Metro Manila Housing Shortage: Developers Rush to Fill the Gap',
    slug: 'metro-manila-housing-shortage',
    category: 'Market Trends',
    image_url: 'https://picsum.photos/seed/realestate2/800/500',
    excerpt: 'With population growth outpacing supply, developers are fast-tracking projects to meet skyrocketing demand...',
    published_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 112,
    title: 'Cavite Industrial Park: OFW Investors Eye Commercial Real Estate',
    slug: 'cavite-industrial-park',
    category: 'Investment',
    image_url: 'https://picsum.photos/seed/realestate3/800/500',
    excerpt: "A new wave of commercial investments from overseas Filipinos is fueling growth in Cavite's industrial zones...",
    published_at: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
  },
]
